export { default as apiClient, extractErrorMessage } from './apiClient'
export { authApi }          from './auth.api'
export { categoriesApi }    from './categories.api'
export { restaurantsApi }   from './restaurants.api'
export { platsApi }         from './plats.api'
export { commandesApi }     from './commandes.api'
export { favorisApi }       from './favoris.api'
export { notificationsApi } from './notifications.api'
export { walletApi }        from './wallet.api'
export { fideliteApi }      from './fidelite.api'
export { avisApi }          from './avis.api'
export { promotionsApi }    from './promotions.api'
export { addressesApi }     from './addresses.api'
export { zonesApi }         from './zones.api'
export { contactApi }       from './contact.api'
export * from './mappers'
